### PR TITLE
Add function to convert from base's Data.Version

### PR DESCRIPTION
**Pull request by adamflott**
Not sure if you're interested in conversion functions, but I am!

(tried matching your style, if I goofed it up, let me know and I'll fix)

### CODE REVIEW

**Comment by tfausak** [comment]
Awesome! Thanks for adding this function. It didn't even occur to me to provide something like this, but it makes total sense. 

I wonder if `convertFromBaseVersion` should ever fail. In other words, it could return `Maybe Version` instead of `Version`. These are the cases I'm concerned about:

- Not having enough version components. Filling in with zeros, as you've done, seems reasonable. But I could see a use case for a "strict" conversion that fails if the version doesn't have enough parts.
- Having too many version components. As above, ignoring them is fine.
- The version's tags could be converted to pre-release identifiers or build metadata, but either of those conversions could fail. 

I think what you've done is good. This isn't a dangerous operation; it's provided for convenience. If someone needs a stricter conversion, they can do it themselves. 

What do you think about also adding a `convertToBaseVersion` for going in the other direction?

**Comment by adamflott** [comment]
You make a good point. I can see too options on this 

1. Easy route `Maybe Version` or `Either String Version`

2. Verbose route

```
data VersionConvertError = VersionConvertMissingPatch
                         | ...
```

Any preference?

And yes, making base's to salve's Version isomorphic does sound like the right thing to do. I'll add that in my next patch

**Comment by tfausak** [comment]
I think providing `Salve.Version -> Data.Version.Version` is fine. No need for `Maybe` or `Either`. The conversion function is total (it's not ever `undefined` or `error "..."`). Some documentation around the edge cases should be enough.

**Comment by tfausak** [comment]
Thanks again for adding this function!

**Comment by tfausak** [comment]
Released in version 0.0.8! https://hackage.haskell.org/package/salve-0.0.8/docs/Salve.html#g:11

**Pull request merged**
